name: kozo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.4.3
  firebase_core: ^3.12.0
  flutter_html: 3.0.0-beta.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/privacy.html
    - assets/images/youtube/1.jpg
    - assets/images/youtube/2.jpg
    - assets/images/youtube/3.jpg
