// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDokOY-bHKO1oSBwzGu7t5uVRs4wadNNPA',
    appId: '1:508074917980:web:00dc8da5e564f6864f6699',
    messagingSenderId: '508074917980',
    projectId: 'kozo-a6926',
    authDomain: 'kozo-a6926.firebaseapp.com',
    storageBucket: 'kozo-a6926.firebasestorage.app',
    measurementId: 'G-Q1JDWFRHX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTljgQhJkopBaj9PcvvZI1GfsTFItGZzQ',
    appId: '1:508074917980:android:c28e975f083cc8164f6699',
    messagingSenderId: '508074917980',
    projectId: 'kozo-a6926',
    storageBucket: 'kozo-a6926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk5ZeYxq-bikRX_4o--BTTLSPAe91RzcQ',
    appId: '1:508074917980:ios:bae5a487998ae3fb4f6699',
    messagingSenderId: '508074917980',
    projectId: 'kozo-a6926',
    storageBucket: 'kozo-a6926.firebasestorage.app',
    iosBundleId: 'com.example.kozo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk5ZeYxq-bikRX_4o--BTTLSPAe91RzcQ',
    appId: '1:508074917980:ios:bae5a487998ae3fb4f6699',
    messagingSenderId: '508074917980',
    projectId: 'kozo-a6926',
    storageBucket: 'kozo-a6926.firebasestorage.app',
    iosBundleId: 'com.example.kozo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuzREQOv4ty0I0BoqaUZZVhWNDtorfRlU',
    appId: '1:508074917980:web:fd25119c3b0614f64f6699',
    messagingSenderId: '508074917980',
    projectId: 'kozo-a6926',
    authDomain: 'kozo-a6926.firebaseapp.com',
    storageBucket: 'kozo-a6926.firebasestorage.app',
    measurementId: 'G-XP7VY2W6VS',
  );
}
